# Generated by Django 5.2.6 on 2025-11-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField()),
                ('email', models.CharField()),
                ('telefone', models.CharField()),
                ('cargo', models.CharField()),
                ('setor', models.CharField()),
                ('turno', models.CharField()),
                ('cpf', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('cnpj', models.CharField()),
                ('email_representante', models.CharField()),
                ('telefone', models.CharField()),
                ('endereco_matriz', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('titulo', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.atividade')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('localizacao', models.CharField()),
                ('lote', models.CharField()),
                ('data_registrada', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('descricao', models.TextField()),
                ('unidade', models.CharField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField()),
                ('lote', models.CharField()),
                ('data_movimentacao', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.categoria')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.produto')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.produto'),
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_incidente', models.DateField()),
                ('descricao', models.TextField()),
                ('tipo', models.CharField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.categoria')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.colaborador')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField()),
                ('data_compra', models.DateField()),
                ('preco_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('status_compras', models.CharField()),
                ('quantidade', models.IntegerField()),
                ('data_entrega_prevista', models.DateField()),
                ('data_entrega_real', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.categoria')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.colaborador')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermes.produto')),
            ],
        ),
    ]
